# Generated by Django 4.0.4 on 2022-08-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instergram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_profile',
        ),
    ]
