# Generated by Django 4.0.4 on 2022-06-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instergram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_user',
            new_name='user',
        ),
    ]
