# Generated by Django 4.0.4 on 2022-08-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instergram', '0002_rename_user_profile_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='user_profiler',
        ),
    ]
