# Generated by Django 4.0.4 on 2022-06-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instergram', '0003_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
