# Generated by Django 4.0.4 on 2022-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instergram', '0003_comment_user_profile_alter_comment_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
