# Generated by Django 4.0.4 on 2022-06-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instergram', '0004_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
